# Deploy a docker image and allocate some resources
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ template "chartName" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ template "chartName" . }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: # TODO: add a descriptive name here
        image: # TODO: add the name of the docker image
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: # TODO: add the port(s) which the container is using
